/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cypherstudios.ad03.view;

/**
 *
 * @author Victor
 */
public class OptionsPanel extends javax.swing.JFrame {

    /**
     * Creates new form OptionsPanel
     */
    public OptionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSmoking = new javax.swing.ButtonGroup();
        btnEnterAllData = new javax.swing.JButton();
        btnDeleteAllData = new javax.swing.JButton();
        jpPassengers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPassengersList = new javax.swing.JTable();
        btnShowPassengers = new javax.swing.JButton();
        labelCodVueloFlights = new javax.swing.JLabel();
        cbxListDestinationFlight = new javax.swing.JComboBox<>();
        btnDisplayFlightPassengers = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnModifyPassengers = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jpPassengerManagement = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodVuelo = new javax.swing.JTextField();
        labelCodVuelo = new javax.swing.JLabel();
        labelNumPassenger = new javax.swing.JLabel();
        labelTipoPlazaPassenger = new javax.swing.JLabel();
        labelFumadorPassenger = new javax.swing.JLabel();
        txtNumPassenger = new javax.swing.JTextField();
        cbxSeatTypePassenger = new javax.swing.JComboBox<>();
        rbtnSmokingYes = new javax.swing.JRadioButton();
        rbtnSmokingNo = new javax.swing.JRadioButton();
        btnSavePassenger = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnterAllData.setText("Dar de alta datos de ejemplo");

        btnDeleteAllData.setText("Eliminar todos los datos");

        jpPassengers.setBorder(javax.swing.BorderFactory.createTitledBorder("PASAJEROS"));

        jtPassengersList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtPassengersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Num", "Vuelo", "Tipo de plaza", "Fumador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPassengersList.setToolTipText("");
        jScrollPane1.setViewportView(jtPassengersList);

        btnShowPassengers.setText("Listar todos los pasajeros");

        labelCodVueloFlights.setText("Selecciona un vuelo:");

        cbxListDestinationFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        btnDisplayFlightPassengers.setText("Ver pasajeros del vuelo");

        btnModifyPassengers.setText("Modificar pasajeros del vuelo");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jpPassengerManagement.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de Pasajeros"));

        jLabel2.setText("Selecciona un pasajero de la tabla para modificarlo");

        txtCodVuelo.setPreferredSize(new java.awt.Dimension(100, 20));

        labelCodVuelo.setText("Cód. Vuelo:");

        labelNumPassenger.setText("Num");

        labelTipoPlazaPassenger.setText("Tipo de plaza");

        labelFumadorPassenger.setText("Fumador");

        txtNumPassenger.setPreferredSize(new java.awt.Dimension(100, 20));

        cbxSeatTypePassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Turista", "Primera" }));

        btnGroupSmoking.add(rbtnSmokingYes);
        rbtnSmokingYes.setText("Si");

        btnGroupSmoking.add(rbtnSmokingNo);
        rbtnSmokingNo.setText("No");

        btnSavePassenger.setText("Guardar");

        javax.swing.GroupLayout jpPassengerManagementLayout = new javax.swing.GroupLayout(jpPassengerManagement);
        jpPassengerManagement.setLayout(jpPassengerManagementLayout);
        jpPassengerManagementLayout.setHorizontalGroup(
            jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPassengerManagementLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpPassengerManagementLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPassengerManagementLayout.createSequentialGroup()
                            .addComponent(btnSavePassenger)
                            .addGap(124, 124, 124)
                            .addComponent(labelFumadorPassenger)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnSmokingYes)
                            .addGap(18, 18, 18)
                            .addComponent(rbtnSmokingNo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPassengerManagementLayout.createSequentialGroup()
                        .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPassengerManagementLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTipoPlazaPassenger))
                            .addGroup(jpPassengerManagementLayout.createSequentialGroup()
                                .addComponent(labelCodVuelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(labelNumPassenger)))
                        .addGap(30, 30, 30)
                        .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSeatTypePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jpPassengerManagementLayout.setVerticalGroup(
            jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPassengerManagementLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumPassenger)
                    .addComponent(txtNumPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodVuelo))
                .addGap(18, 18, 18)
                .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSeatTypePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoPlazaPassenger))
                .addGap(18, 18, 18)
                .addGroup(jpPassengerManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSmokingYes)
                    .addComponent(rbtnSmokingNo)
                    .addComponent(labelFumadorPassenger)
                    .addComponent(btnSavePassenger))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPassengersLayout = new javax.swing.GroupLayout(jpPassengers);
        jpPassengers.setLayout(jpPassengersLayout);
        jpPassengersLayout.setHorizontalGroup(
            jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPassengersLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowPassengers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPassengersLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jpPassengersLayout.createSequentialGroup()
                                .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDisplayFlightPassengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCodVueloFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxListDestinationFlight, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModifyPassengers)))))
                    .addGroup(jpPassengersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPassengerManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jpPassengersLayout.setVerticalGroup(
            jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPassengersLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPassengersLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnShowPassengers))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPassengersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodVueloFlights)
                            .addComponent(cbxListDestinationFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDisplayFlightPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifyPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jpPassengerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnExit.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnEnterAllData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(btnDeleteAllData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterAllData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAllData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteAllData;
    public javax.swing.JButton btnDisplayFlightPassengers;
    public javax.swing.JButton btnEnterAllData;
    public javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupSmoking;
    public javax.swing.JButton btnModifyPassengers;
    public javax.swing.JButton btnSavePassenger;
    public javax.swing.JButton btnShowPassengers;
    public javax.swing.JComboBox<String> cbxListDestinationFlight;
    public javax.swing.JComboBox<String> cbxSeatTypePassenger;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel jpPassengerManagement;
    public javax.swing.JPanel jpPassengers;
    public javax.swing.JTable jtPassengersList;
    private javax.swing.JLabel labelCodVuelo;
    public javax.swing.JLabel labelCodVueloFlights;
    public javax.swing.JLabel labelFumadorPassenger;
    public javax.swing.JLabel labelNumPassenger;
    public javax.swing.JLabel labelTipoPlazaPassenger;
    public javax.swing.JRadioButton rbtnSmokingNo;
    public javax.swing.JRadioButton rbtnSmokingYes;
    public javax.swing.JTextField txtCodVuelo;
    public javax.swing.JTextField txtNumPassenger;
    // End of variables declaration//GEN-END:variables
}
